export const countryNames: Record<string, string> = {
  de: 'Germany',
  us: 'United States',
  ad: 'Andorra',
  ae: 'United Arab Emirates',
  af: 'Afghanistan',
  ag: 'Antigua and Barbuda',
  ai: 'Anguilla',
  al: 'Albania',
  am: 'Armenia',
  ao: 'Angola',
  ar: 'Argentina',
  as: 'American Samoa',
  at: 'Austria',
  au: 'Australia',
  aw: 'Aruba',
  ax: 'Åland Islands',
  az: 'Azerbaijan',
  ba: 'Bosnia and Herzegovina',
  bb: 'Barbados',
  bd: 'Bangladesh',
  be: 'Belgium',
  bf: 'Burkina Faso',
  bg: 'Bulgaria',
  bh: 'Bahrain',
  bi: 'Burundi',
  bj: 'Benin',
  bl: 'Saint Barthélemy',
  bm: 'Bermuda',
  bn: 'Brunei Darussalam',
  bo: 'Bolivia',
  bq: 'Bonaire, Sint Eustatius and Saba',
  br: 'Brazil',
  bs: 'Bahamas',
  bt: 'Bhutan',
  bv: 'Bouvet Island',
  bw: 'Botswana',
  by: 'Belarus',
  bz: 'Belize',
  ca: 'Canada',
  cc: 'Cocos (Keeling) Islands',
  cd: 'Congo, Democratic Republic of the',
  cf: 'Central African Republic',
  cg: 'Congo',
  ch: 'Switzerland',
  ci: "Côte d'Ivoire",
  ck: 'Cook Islands',
  cl: 'Chile',
  cm: 'Cameroon',
  cn: 'China',
  co: 'Colombia',
  cr: 'Costa Rica',
  cu: 'Cuba',
  cv: 'Cabo Verde',
  cw: 'Curaçao',
  cx: 'Christmas Island',
  cy: 'Cyprus',
  cz: 'Czechia',
  dj: 'Djibouti',
  dk: 'Denmark',
  dm: 'Dominica',
  do: 'Dominican Republic',
  dz: 'Algeria',
  ec: 'Ecuador',
  ee: 'Estonia',
  eg: 'Egypt',
  es: 'Spain',
  et: 'Ethiopia',
  fi: 'Finland',
  fj: 'Fiji',
  fm: 'Micronesia, Federated States of',
  fo: 'Faroe Islands',
  fr: 'France',
  ga: 'Gabon',
  gb: 'United Kingdom',
  gd: 'Grenada',
  ge: 'Georgia',
  gh: 'Ghana',
  gi: 'Gibraltar',
  gl: 'Greenland',
  gm: 'Gambia',
  gn: 'Guinea',
  gp: 'Guadeloupe',
  gq: 'Equatorial Guinea',
  gr: 'Greece',
  gs: 'South Georgia and the South Sandwich Islands',
  gt: 'Guatemala',
  gu: 'Guam',
  gw: 'Guinea-Bissau',
  gy: 'Guyana',
  hk: 'Hong Kong',
  hn: 'Honduras',
  hr: 'Croatia',
  ht: 'Haiti',
  hu: 'Hungary',
  id: 'Indonesia',
  ie: 'Ireland',
  il: 'Israel',
  im: 'Isle of Man',
  in: 'India',
  iq: 'Iraq',
  ir: 'Iran',
  is: 'Iceland',
  it: 'Italy',
  je: 'Jersey',
  jm: 'Jamaica',
  jo: 'Jordan',
  jp: 'Japan',
  ke: 'Kenya',
  kg: 'Kyrgyzstan',
  kh: 'Cambodia',
  ki: 'Kiribati',
  km: 'Comoros',
  kn: 'Saint Kitts and Nevis',
  kp: 'North Korea',
  kr: 'South Korea',
  kw: 'Kuwait',
  ky: 'Cayman Islands',
  kz: 'Kazakhstan',
  la: 'Laos',
  lb: 'Lebanon',
  lc: 'Saint Lucia',
  li: 'Liechtenstein',
  lk: 'Sri Lanka',
  lr: 'Liberia',
  ls: 'Lesotho',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  lv: 'Latvia',
  ly: 'Libya',
  ma: 'Morocco',
  mc: 'Monaco',
  md: 'Moldova',
  me: 'Montenegro',
  mf: 'Saint Martin (French part)',
  mg: 'Madagascar',
  mh: 'Marshall Islands',
  mk: 'North Macedonia',
  ml: 'Mali',
  mm: 'Myanmar',
  mn: 'Mongolia',
  mo: 'Macao',
  mp: 'Northern Mariana Islands',
  mq: 'Martinique',
  mr: 'Mauritania',
  ms: 'Montserrat',
  mt: 'Malta',
  mu: 'Mauritius',
  mv: 'Maldives',
  mw: 'Malawi',
  mx: 'Mexico',
  my: 'Malaysia',
  mz: 'Mozambique',
  na: 'Namibia',
  nc: 'New Caledonia',
  ne: 'Niger',
  nf: 'Norfolk Island',
  ng: 'Nigeria',
  ni: 'Nicaragua',
  nl: 'Netherlands',
  no: 'Norway',
  np: 'Nepal',
  nr: 'Nauru',
  nu: 'Niue',
  nz: 'New Zealand',
  om: 'Oman',
  pa: 'Panama',
  pe: 'Peru',
  pf: 'French Polynesia',
  pg: 'Papua New Guinea',
  ph: 'Philippines',
  pk: 'Pakistan',
  pl: 'Poland',
  pr: 'Puerto Rico',
  ps: 'Palestine',
  pt: 'Portugal',
  pw: 'Palau',
  py: 'Paraguay',
  qa: 'Qatar',
  re: 'Réunion',
  ro: 'Romania',
  rs: 'Serbia',
  ru: 'Russia',
  rw: 'Rwanda',
  sa: 'Saudi Arabia',
  sb: 'Solomon Islands',
  sc: 'Seychelles',
  sd: 'Sudan',
  se: 'Sweden',
  sg: 'Singapore',
  sh: 'Saint Helena',
  si: 'Slovenia',
  sj: 'Svalbard and Jan Mayen',
  sk: 'Slovakia',
  sl: 'Sierra Leone',
  sm: 'San Marino',
  sn: 'Senegal',
  so: 'Somalia',
  sr: 'Suriname',
  ss: 'South Sudan',
  st: 'São Tomé and Príncipe',
  sv: 'El Salvador',
  sy: 'Syria',
  sz: 'Eswatini',
  tc: 'Turks and Caicos Islands',
  td: 'Chad',
  tg: 'Togo',
  th: 'Thailand',
  tj: 'Tajikistan',
  tk: 'Tokelau',
  tl: 'Timor-Leste',
  tm: 'Turkmenistan',
  tn: 'Tunisia',
  to: 'Tonga',
  tr: 'Turkey',
  tt: 'Trinidad and Tobago',
  tv: 'Tuvalu',
  tz: 'Tanzania',
  ua: 'Ukraine',
  ug: 'Uganda',
  uy: 'Uruguay',
  uz: 'Uzbekistan',
  va: 'Vatican City',
  vc: 'Saint Vincent and the Grenadines',
  ve: 'Venezuela',
  vn: 'Vietnam',
  vu: 'Vanuatu',
  ws: 'Samoa',
  ye: 'Yemen',
  za: 'South Africa',
  zm: 'Zambia',
  zw: 'Zimbabwe',
};

export const countryFlags: Record<string, string> = {
  de: 'https://flagcdn.com/w320/de.png',
  us: 'https://flagcdn.com/w320/us.png',
  ad: 'https://flagcdn.com/w320/ad.png',
  ae: 'https://flagcdn.com/w320/ae.png',
  af: 'https://flagcdn.com/w320/af.png',
  ag: 'https://flagcdn.com/w320/ag.png',
  ai: 'https://flagcdn.com/w320/ai.png',
  al: 'https://flagcdn.com/w320/al.png',
  am: 'https://flagcdn.com/w320/am.png',
  ao: 'https://flagcdn.com/w320/ao.png',
  ar: 'https://flagcdn.com/w320/ar.png',
  as: 'https://flagcdn.com/w320/as.png',
  at: 'https://flagcdn.com/w320/at.png',
  au: 'https://flagcdn.com/w320/au.png',
  aw: 'https://flagcdn.com/w320/aw.png',
  ax: 'https://flagcdn.com/w320/ax.png',
  az: 'https://flagcdn.com/w320/az.png',
  ba: 'https://flagcdn.com/w320/ba.png',
  bb: 'https://flagcdn.com/w320/bb.png',
  bd: 'https://flagcdn.com/w320/bd.png',
  be: 'https://flagcdn.com/w320/be.png',
  bf: 'https://flagcdn.com/w320/bf.png',
  bg: 'https://flagcdn.com/w320/bg.png',
  bh: 'https://flagcdn.com/w320/bh.png',
  bi: 'https://flagcdn.com/w320/bi.png',
  bj: 'https://flagcdn.com/w320/bj.png',
  bl: 'https://flagcdn.com/w320/bl.png',
  bm: 'https://flagcdn.com/w320/bm.png',
  bn: 'https://flagcdn.com/w320/bn.png',
  bo: 'https://flagcdn.com/w320/bo.png',
  bq: 'https://flagcdn.com/w320/bq.png',
  br: 'https://flagcdn.com/w320/br.png',
  bs: 'https://flagcdn.com/w320/bs.png',
  bt: 'https://flagcdn.com/w320/bt.png',
  bv: 'https://flagcdn.com/w320/bv.png',
  bw: 'https://flagcdn.com/w320/bw.png',
  by: 'https://flagcdn.com/w320/by.png',
  bz: 'https://flagcdn.com/w320/bz.png',
  ca: 'https://flagcdn.com/w320/ca.png',
  cc: 'https://flagcdn.com/w320/cc.png',
  cd: 'https://flagcdn.com/w320/cd.png',
  cf: 'https://flagcdn.com/w320/cf.png',
  cg: 'https://flagcdn.com/w320/cg.png',
  ch: 'https://flagcdn.com/w320/ch.png',
  ci: 'https://flagcdn.com/w320/ci.png',
  ck: 'https://flagcdn.com/w320/ck.png',
  cl: 'https://flagcdn.com/w320/cl.png',
  cm: 'https://flagcdn.com/w320/cm.png',
  cn: 'https://flagcdn.com/w320/cn.png',
  co: 'https://flagcdn.com/w320/co.png',
  cr: 'https://flagcdn.com/w320/cr.png',
  cu: 'https://flagcdn.com/w320/cu.png',
  cv: 'https://flagcdn.com/w320/cv.png',
  cw: 'https://flagcdn.com/w320/cw.png',
  cx: 'https://flagcdn.com/w320/cx.png',
  cy: 'https://flagcdn.com/w320/cy.png',
  cz: 'https://flagcdn.com/w320/cz.png',
  dj: 'https://flagcdn.com/w320/dj.png',
  dk: 'https://flagcdn.com/w320/dk.png',
  dm: 'https://flagcdn.com/w320/dm.png',
  do: 'https://flagcdn.com/w320/do.png',
  dz: 'https://flagcdn.com/w320/dz.png',
  ec: 'https://flagcdn.com/w320/ec.png',
  ee: 'https://flagcdn.com/w320/ee.png',
  eg: 'https://flagcdn.com/w320/eg.png',
  es: 'https://flagcdn.com/w320/es.png',
  et: 'https://flagcdn.com/w320/et.png',
  fi: 'https://flagcdn.com/w320/fi.png',
  fj: 'https://flagcdn.com/w320/fj.png',
  fm: 'https://flagcdn.com/w320/fm.png',
  fo: 'https://flagcdn.com/w320/fo.png',
  fr: 'https://flagcdn.com/w320/fr.png',
  ga: 'https://flagcdn.com/w320/ga.png',
  gb: 'https://flagcdn.com/w320/gb.png',
  gd: 'https://flagcdn.com/w320/gd.png',
  ge: 'https://flagcdn.com/w320/ge.png',
  gh: 'https://flagcdn.com/w320/gh.png',
  gi: 'https://flagcdn.com/w320/gi.png',
  gl: 'https://flagcdn.com/w320/gl.png',
  gm: 'https://flagcdn.com/w320/gm.png',
  gn: 'https://flagcdn.com/w320/gn.png',
  gp: 'https://flagcdn.com/w320/gp.png',
  gq: 'https://flagcdn.com/w320/gq.png',
  gr: 'https://flagcdn.com/w320/gr.png',
  gs: 'https://flagcdn.com/w320/gs.png',
  gt: 'https://flagcdn.com/w320/gt.png',
  gu: 'https://flagcdn.com/w320/gu.png',
  gw: 'https://flagcdn.com/w320/gw.png',
  gy: 'https://flagcdn.com/w320/gy.png',
  hk: 'https://flagcdn.com/w320/hk.png',
  hn: 'https://flagcdn.com/w320/hn.png',
  hr: 'https://flagcdn.com/w320/hr.png',
  ht: 'https://flagcdn.com/w320/ht.png',
  hu: 'https://flagcdn.com/w320/hu.png',
  id: 'https://flagcdn.com/w320/id.png',
  ie: 'https://flagcdn.com/w320/ie.png',
  il: 'https://flagcdn.com/w320/il.png',
  im: 'https://flagcdn.com/w320/im.png',
  in: 'https://flagcdn.com/w320/in.png',
  iq: 'https://flagcdn.com/w320/iq.png',
  ir: 'https://flagcdn.com/w320/ir.png',
  is: 'https://flagcdn.com/w320/is.png',
  it: 'https://flagcdn.com/w320/it.png',
  je: 'https://flagcdn.com/w320/je.png',
  jm: 'https://flagcdn.com/w320/jm.png',
  jo: 'https://flagcdn.com/w320/jo.png',
  jp: 'https://flagcdn.com/w320/jp.png',
  ke: 'https://flagcdn.com/w320/ke.png',
  kg: 'https://flagcdn.com/w320/kg.png',
  kh: 'https://flagcdn.com/w320/kh.png',
  ki: 'https://flagcdn.com/w320/ki.png',
  km: 'https://flagcdn.com/w320/km.png',
  kn: 'https://flagcdn.com/w320/kn.png',
  kp: 'https://flagcdn.com/w320/kp.png',
  kr: 'https://flagcdn.com/w320/kr.png',
  kw: 'https://flagcdn.com/w320/kw.png',
  ky: 'https://flagcdn.com/w320/ky.png',
  kz: 'https://flagcdn.com/w320/kz.png',
  la: 'https://flagcdn.com/w320/la.png',
  lb: 'https://flagcdn.com/w320/lb.png',
  lc: 'https://flagcdn.com/w320/lc.png',
  li: 'https://flagcdn.com/w320/li.png',
  lk: 'https://flagcdn.com/w320/lk.png',
  lr: 'https://flagcdn.com/w320/lr.png',
  ls: 'https://flagcdn.com/w320/ls.png',
  lt: 'https://flagcdn.com/w320/lt.png',
  lu: 'https://flagcdn.com/w320/lu.png',
  lv: 'https://flagcdn.com/w320/lv.png',
  ly: 'https://flagcdn.com/w320/ly.png',
  ma: 'https://flagcdn.com/w320/ma.png',
  mc: 'https://flagcdn.com/w320/mc.png',
  md: 'https://flagcdn.com/w320/md.png',
  me: 'https://flagcdn.com/w320/me.png',
  mf: 'https://flagcdn.com/w320/mf.png',
  mg: 'https://flagcdn.com/w320/mg.png',
  mh: 'https://flagcdn.com/w320/mh.png',
  mk: 'https://flagcdn.com/w320/mk.png',
  ml: 'https://flagcdn.com/w320/ml.png',
  mm: 'https://flagcdn.com/w320/mm.png',
  mn: 'https://flagcdn.com/w320/mn.png',
  mo: 'https://flagcdn.com/w320/mo.png',
  mp: 'https://flagcdn.com/w320/mp.png',
  mq: 'https://flagcdn.com/w320/mq.png',
  mr: 'https://flagcdn.com/w320/mr.png',
  ms: 'https://flagcdn.com/w320/ms.png',
  mt: 'https://flagcdn.com/w320/mt.png',
  mu: 'https://flagcdn.com/w320/mu.png',
  mv: 'https://flagcdn.com/w320/mv.png',
  mw: 'https://flagcdn.com/w320/mw.png',
  mx: 'https://flagcdn.com/w320/mx.png',
  my: 'https://flagcdn.com/w320/my.png',
  mz: 'https://flagcdn.com/w320/mz.png',
  na: 'https://flagcdn.com/w320/na.png',
  nc: 'https://flagcdn.com/w320/nc.png',
  ne: 'https://flagcdn.com/w320/ne.png',
  nf: 'https://flagcdn.com/w320/nf.png',
  ng: 'https://flagcdn.com/w320/ng.png',
  ni: 'https://flagcdn.com/w320/ni.png',
  nl: 'https://flagcdn.com/w320/nl.png',
  no: 'https://flagcdn.com/w320/no.png',
  np: 'https://flagcdn.com/w320/np.png',
  nr: 'https://flagcdn.com/w320/nr.png',
  nu: 'https://flagcdn.com/w320/nu.png',
  nz: 'https://flagcdn.com/w320/nz.png',
  om: 'https://flagcdn.com/w320/om.png',
  pa: 'https://flagcdn.com/w320/pa.png',
  pe: 'https://flagcdn.com/w320/pe.png',
  pf: 'https://flagcdn.com/w320/pf.png',
  pg: 'https://flagcdn.com/w320/pg.png',
  ph: 'https://flagcdn.com/w320/ph.png',
  pk: 'https://flagcdn.com/w320/pk.png',
  pl: 'https://flagcdn.com/w320/pl.png',
  pr: 'https://flagcdn.com/w320/pr.png',
  ps: 'https://flagcdn.com/w320/ps.png',
  pt: 'https://flagcdn.com/w320/pt.png',
  pw: 'https://flagcdn.com/w320/pw.png',
  py: 'https://flagcdn.com/w320/py.png',
  qa: 'https://flagcdn.com/w320/qa.png',
  re: 'https://flagcdn.com/w320/re.png',
  ro: 'https://flagcdn.com/w320/ro.png',
  rs: 'https://flagcdn.com/w320/rs.png',
  ru: 'https://flagcdn.com/w320/ru.png',
  rw: 'https://flagcdn.com/w320/rw.png',
  sa: 'https://flagcdn.com/w320/sa.png',
  sb: 'https://flagcdn.com/w320/sb.png',
  sc: 'https://flagcdn.com/w320/sc.png',
  sd: 'https://flagcdn.com/w320/sd.png',
  se: 'https://flagcdn.com/w320/se.png',
  sg: 'https://flagcdn.com/w320/sg.png',
  sh: 'https://flagcdn.com/w320/sh.png',
  si: 'https://flagcdn.com/w320/si.png',
  sj: 'https://flagcdn.com/w320/sj.png',
  sk: 'https://flagcdn.com/w320/sk.png',
  sl: 'https://flagcdn.com/w320/sl.png',
  sm: 'https://flagcdn.com/w320/sm.png',
  sn: 'https://flagcdn.com/w320/sn.png',
  so: 'https://flagcdn.com/w320/so.png',
  sr: 'https://flagcdn.com/w320/sr.png',
  ss: 'https://flagcdn.com/w320/ss.png',
  st: 'https://flagcdn.com/w320/st.png',
  sv: 'https://flagcdn.com/w320/sv.png',
  sy: 'https://flagcdn.com/w320/sy.png',
  sz: 'https://flagcdn.com/w320/sz.png',
  tc: 'https://flagcdn.com/w320/tc.png',
  td: 'https://flagcdn.com/w320/td.png',
  tg: 'https://flagcdn.com/w320/tg.png',
  th: 'https://flagcdn.com/w320/th.png',
  tj: 'https://flagcdn.com/w320/tj.png',
  tk: 'https://flagcdn.com/w320/tk.png',
  tl: 'https://flagcdn.com/w320/tl.png',
  tm: 'https://flagcdn.com/w320/tm.png',
  tn: 'https://flagcdn.com/w320/tn.png',
  to: 'https://flagcdn.com/w320/to.png',
  tr: 'https://flagcdn.com/w320/tr.png',
  tt: 'https://flagcdn.com/w320/tt.png',
  tv: 'https://flagcdn.com/w320/tv.png',
  tz: 'https://flagcdn.com/w320/tz.png',
  ua: 'https://flagcdn.com/w320/ua.png',
  ug: 'https://flagcdn.com/w320/ug.png',
  uy: 'https://flagcdn.com/w320/uy.png',
  uz: 'https://flagcdn.com/w320/uz.png',
  va: 'https://flagcdn.com/w320/va.png',
  vc: 'https://flagcdn.com/w320/vc.png',
  ve: 'https://flagcdn.com/w320/ve.png',
  vg: 'https://flagcdn.com/w320/vg.png',
  vi: 'https://flagcdn.com/w320/vi.png',
  vn: 'https://flagcdn.com/w320/vn.png',
  vu: 'https://flagcdn.com/w320/vu.png',
  wf: 'https://flagcdn.com/w320/wf.png',
  ws: 'https://flagcdn.com/w320/ws.png',
  ye: 'https://flagcdn.com/w320/ye.png',
  yt: 'https://flagcdn.com/w320/yt.png',
  za: 'https://flagcdn.com/w320/za.png',
  zm: 'https://flagcdn.com/w320/zm.png',
  zw: 'https://flagcdn.com/w320/zw.png',
};
